### ISSUE TITLE
Sugerencias de Gonzalo

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/GsX26-instagram-feed-con-bootstrap#1]
Buenas Héctor, he subido el proyecto de Instagram feed con boostrap. Tengo 3cuestiones:
1- Confirmar que está bien subido que no falta nada.
2- El botón de crear post no obedece siempre y no entiendo porqué
3- Me puedes indicar como se crea el issues dentro del proyecto para poner estas consultas?

Gracias,

**Comment by hchocobar** [comment]
# Review

1. Faltaba subirlo a GitHub (ya realizado).
2. 

- Recuerda agregar las clases `d-flex justify-content-center` para lograr de que los botones y las imagenes estén centradas en tu diseño (en la imagen te indico donde escribirlas).

![Captura desde 2023-07-25 15-45-00](https://github.com/4GeeksAcademy/GsX26-instagram-feed-con-bootstrap/assets/45291267/476eb8bc-cdc7-4268-b028-f506a8f10621)

- Gonzalo faltan muchos `</div>` y eso ocasiona que tu sitio se comporte de manera extraña.

**Comment by GsX26** [comment]
Hecho! Lo que me falta es eliminar las cards de la galería

**Comment by hchocobar** [comment]
Muy buen trabajo Gonzalo!
